/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#fea619",
        outline: "#6e7980",
        "on-secondary-fixed": "#2a1700",
        secondary: "#855300",
        "secondary-fixed": "#ffddb8",
        "on-primary": "#ffffff",
        surface: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#6bff8f",
        "on-tertiary-fixed": "#002109",
        "primary-container": "#38bdf8",
        "on-secondary-fixed-variant": "#653e00",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#004f20",
        "surface-tint": "#00668a",
        "on-surface": "#0b1c30",
        background: "#f8f9ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005321",
        "tertiary-fixed-dim": "#4ae176",
        "secondary-fixed-dim": "#ffb95f",
        "on-primary-fixed-variant": "#004c69",
        "outline-variant": "#bdc8d1",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#2ccb63",
        "surface-container": "#e5eeff",
        "inverse-primary": "#7bd0ff",
        "on-primary-container": "#004965",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#684000",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001e2c",
        tertiary: "#006e2f",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#7bd0ff",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed": "#c4e7ff",
        "on-background": "#0b1c30",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3e484f",
        primary: "#00668a",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
